AWSTemplateFormatVersion: '2010-09-09'
Description: "AWS Organizations using Cloudformation - Creates OU, nested OU, account and organizations policies"

Parameters:
  OrganizationRoot:
    Description: 'Organization ID'
    Type: String
  Email:
    Description: 'Email to create accounts'
    Type: String

Resources:
  Sandbox:
    Type: AWS::Organizations::Account
    Properties:
      AccountName: 'sandbox'
      Email: !Sub
        - '${Usr}+sandbox@${Domain}'
        - Usr: !Select [0, !Split ["@", !Ref Email]]
        - Domain: !Select [1, !Split ["@", !Ref Email]]
      ParentIds:
        - !Ref OrganizationRoot