AWSTemplateFormatVersion: "2010-09-09"
Description: "Pipeline"

Parameters:
  ConnectionArn:
    Description: Github Connection arn
    Type: String
  Account:
    Description: Repo account name
    Type: String
  Repo:
    Description: Repo name
    Type: String
  Stage:
    Description: Stage
    Type: String
  Branch:
    Description: Branch name
    Type: String

Resources:
  CodeBuildRole:
    Type: 'AWS::IAM::Role'
    Properties:
      Description: "Role for CodeBuild project"
      RoleName: !Sub "${Repo}-${Stage}-CodeBuildRole"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service:
                - 'codebuild.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'CodeBuildRolePolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:PutObject'
                Resource: '*'

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub "${Repo}-${Stage}-${Branch}-CodeBuildProject"
      Description: "Test description"
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/standard:7.0"
        Type: "LINUX_CONTAINER"
      Source:
        Type: "CODEPIPELINE"
        GitCloneDepth: 1
        BuildSpec: |
          version: 0.2

          phases:
            build:
              commands:
                - pwd
                - ls
                - echo "Getting here"
                - go version
                - go run .
      Artifacts:
        Type: "CODEPIPELINE"
      TimeoutInMinutes: 60

  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "${Repo}-${Stage}-${Branch}-artifactstorebucket"
      VersioningConfiguration:
        Status: Enabled

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    DependsOn: CodeBuildProject
    Properties:
      Name: !Sub "${Repo}-${Stage}-${Branch}"
      ArtifactStore:
        Location: !Ref ArtifactStoreBucket
        Type: S3
      RoleArn:
        Fn::ImportValue: !Sub "root-${Stage}-CodePipelineRole"
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              RunOrder: 1
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArn
                FullRepositoryId: !Sub "${Account}/${Repo}"
                BranchName: !Ref Branch
                OutputArtifactFormat: "CODE_ZIP"
                DetectChanges: "true"
              Namespace: SourceVariables
              OutputArtifacts:
                - Name: SourceArtifact
        - Name: Approval
          Actions:
            - Name: Approval
              RunOrder: 1
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              Configuration:
                CustomData: "Manual Approval"
        - Name: Build
          Actions:
            - Name: Build
              RunOrder: 1
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
