AWSTemplateFormatVersion: "2010-09-09"
Description: "Permissions"

Parameters:
  AwsSsoArn:
    Description: "AWS SSO ARN"
    Type: String
  AccountId:
    Description: "Account id"
    Type: String
  AdminGroupId:
    Description: "Admin group id"
    Type: String
  OperationsGroupId:
    Description: "Operations group id"
    Type: String
  DeveloperGroupId:
    Description: "Developer group id"
    Type: String

Resources:
  AdminPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: "Admin"
      Description: "Admin access to AWS organization"
      InstanceArn: !Ref AwsSsoArn
      SessionDuration: "PT8H"
      InlinePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "AdminDefaultAccess"
            Effect: "Allow"
            Action:
              - "*"
            Resource:
              - "*"

  AdminAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref AwsSsoArn
      PermissionSetArn: !GetAtt AdminPermissionSet.PermissionSetArn
      PrincipalId: !Ref AdminGroupId
      PrincipalType: GROUP
      TargetId: !Ref AccountId
      TargetType: "AWS_ACCOUNT"

  RootAdminAssigment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref AwsSsoArn
      PermissionSetArn: !GetAtt AdminPermissionSet.PermissionSetArn
      PrincipalId: !Ref AdminGroupId
      PrincipalType: GROUP
      TargetId: !Ref "AWS::AccountId"
      TargetType: "AWS_ACCOUNT"

  OperationsPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: "Operations"
      Description: "Operations access to AWS organization"
      InstanceArn: !Ref AwsSsoArn
      SessionDuration: "PT8H"
      ManagedPolicies:
        - arn:aws:iam::aws:policy/IAMReadOnlyAccess
      InlinePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "OperationsDefaultAccess"
            Effect: "Allow"
            Action:
              - "codepipeline:*"
              - "cloudwatch:*"
              - "dynamodb:*"
              - "lambda:*"
              - "logs:*"
              - "s3:*"
            Resource:
              - "*"

  OperationsAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref AwsSsoArn
      PermissionSetArn: !GetAtt OperationsPermissionSet.PermissionSetArn
      PrincipalId: !Ref OperationsGroupId
      PrincipalType: GROUP
      TargetId: !Ref AccountId
      TargetType: "AWS_ACCOUNT"

  DevPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: "Developer"
      Description: "Developer access to AWS organization"
      InstanceArn: !Ref AwsSsoArn
      SessionDuration: "PT8H"
      InlinePolicy:
        Version: "2012-10-17"
        Statement:
          - Sid: "DeveloperDefaultAccess"
            Effect: "Allow"
            Action:
              - "account:ListRegions"
              - "cloudwatch:*"
              - "dynamodb:*"
              - "lambda:*"
              - "logs:*"
              - "s3:*"
            Resource:
              - "*"

  DevAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref AwsSsoArn
      PermissionSetArn: !GetAtt DevPermissionSet.PermissionSetArn
      PrincipalId: !Ref DeveloperGroupId
      PrincipalType: GROUP
      TargetId: !Ref AccountId
      TargetType: "AWS_ACCOUNT"
